/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HerIHKPDoM4
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import Link from "next/link";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { MailIcon, KeyIcon, CheckIcon, ClockIcon } from "lucide-react";
import { ProjectDto } from "@/use-cases/project/types";
import { UserDto } from "@/use-cases/user/types";
import { getInitials } from "@/app/utils/getInitials";
type MemberCardWithPermissionsProps = {
  user: UserDto;
  project: ProjectDto;
};
export function MemberCardWithPermissions({
  user,
  project,
}: MemberCardWithPermissionsProps) {
  return (
    <Card className="w-full max-w-sm mx-auto">
      <CardHeader className="pb-0">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-3">
            <Avatar className="w-10 h-10">
              <AvatarImage alt={user.name} src="@/public/default-avatar.jpg" />
              <AvatarFallback>{getInitials(user.name)}</AvatarFallback>
            </Avatar>
            <div className="text-lg font-bold">{user.name}</div>
          </div>
          <div className="ml-auto flex items-center space-x-2">
            <Badge variant="outline">{user.tasks.length} tasks</Badge>
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-0 space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center space-x-2">
            <MailIcon className="w-4 h-4 opacity-60" />
            <span className="text-sm font-medium">Email</span>
          </div>
          <div className="text-right">
            <Link className="text-sm font-medium underline" href="#">
              Change email
            </Link>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center space-x-2">
            <KeyIcon className="w-4 h-4 opacity-60" />
            <span className="text-sm font-medium">Role</span>
          </div>
          <div className="text-right">
            <Select>
              <SelectTrigger>
                <SelectValue>Admin</SelectValue>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="admin">Admin</SelectItem>
                <SelectItem value="member">Member</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center space-x-2">
            <CheckIcon className="w-4 h-4 opacity-60" />
            <span className="text-sm font-medium">Tasks Completed</span>
          </div>
          <div className="text-right">
            <span className="text-sm font-medium">10</span>
          </div>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="flex items-center space-x-2">
            <ClockIcon className="w-4 h-4 opacity-60" />
            <span className="text-sm font-medium">Active Tasks</span>
          </div>
          <div className="text-right">
            <span className="text-sm font-medium">2</span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
