/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/udPqnm5kC5j
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function MemberCard() {
  return (
    <Card>
      <CardHeader className="p-6">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2">
            <Avatar className="w-10 h-10">
              <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div className="text-lg font-bold">Jared Palmer</div>
          </div>
          <div className="text-sm font-medium text-gray-500 dark:text-gray-400">example@acme.inc</div>
        </div>
      </CardHeader>
      <CardContent className="p-6">
        <div className="flex items-center space-x-2">
          <CheckCircleIcon className="h-4 w-4 text-green-500" />
          <div className="text-sm font-medium">Admin</div>
        </div>
        <div className="flex items-center space-x-2">
          <ActivityIcon className="h-4 w-4" />
          <div className="text-sm font-medium">3 active tasks</div>
        </div>
        <div className="flex items-center space-x-2">
          <CalendarDaysIcon className="h-4 w-4 opacity-70" />
          <div className="text-xs text-gray-500 dark:text-gray-400">Member since yesterday</div>
        </div>
      </CardContent>
    </Card>
  )
}


function CheckCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}


function ActivityIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  )
}


function CalendarDaysIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="M8 14h.01" />
      <path d="M12 14h.01" />
      <path d="M16 14h.01" />
      <path d="M8 18h.01" />
      <path d="M12 18h.01" />
      <path d="M16 18h.01" />
    </svg>
  )
}
