/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/udPqnm5kC5j
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { CardHeader, CardContent, Card } from "@/components/ui/card";
import { CheckCircleIcon, ActivityIcon, CalendarDaysIcon } from "lucide-react";

export function MemberCard() {
  return (
    <Card>
      <CardHeader className="p-6">
        <div className="flex items-center space-x-4">
          <div className="flex items-center space-x-2">
            <Avatar className="w-10 h-10">
              <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div className="text-lg font-bold">Jared Palmer</div>
          </div>
          <div className="text-sm font-medium text-gray-500 dark:text-gray-400">
            example@acme.inc
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6">
        <div className="flex items-center space-x-2">
          <CheckCircleIcon className="h-4 w-4 text-green-500" />
          <div className="text-sm font-medium">Admin</div>
        </div>
        <div className="flex items-center space-x-2">
          <ActivityIcon className="h-4 w-4" />
          <div className="text-sm font-medium">3 active tasks</div>
        </div>
        <div className="flex items-center space-x-2">
          <CalendarDaysIcon className="h-4 w-4 opacity-70" />
          <div className="text-xs text-gray-500 dark:text-gray-400">
            Member since yesterday
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
