/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lYDJqrfbG1H
 */
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";

export function ProjectsSection() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-gray-200 dark:bg-gray-900">
      <header className="flex items-center h-16 px-4 border-b border-gray-300 dark:border-gray-700 shrink-0 md:px-6">
        <Link
          className="flex items-center gap-2 text-lg font-semibold sm:text-base mr-4 text-gray-700 dark:text-gray-300"
          href="#"
        >
          <FrameIcon className="w-6 h-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] bg-gray-100/40 flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10 dark:bg-gray-800/40">
        <div className="max-w-6xl w-full mx-auto flex items-center gap-4">
          <form className="flex-1 flex gap-2">
            <Input
              className="bg-white dark:bg-gray-950 flex-grow"
              placeholder="Search projects..."
            />
            <Button type="submit">Search</Button>
          </form>
        </div>
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 max-w-6xl w-full mx-auto">
          <Card className="bg-white dark:bg-gray-800">
            <CardHeader className="flex flex-row items-center gap-4">
              <HomeIcon className="w-8 h-8 text-green-500 dark:text-green-300" />
              <div className="grid gap-1">
                <CardTitle>Project 1</CardTitle>
                <CardDescription>project1.com</CardDescription>
              </div>
              <Button className="ml-auto" size="icon" variant="ghost">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle menu</span>
              </Button>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold">Active Tasks: 10</div>
              <div className="text-sm font-semibold">Your Current Tasks: 3</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <UsersIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">
                    5 Members
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-white dark:bg-gray-800">
            <CardHeader className="flex flex-row items-center gap-4">
              <BookOpenIcon className="w-8 h-8 text-blue-500 dark:text-blue-300" />
              <div className="grid gap-1">
                <CardTitle>Project 2</CardTitle>
                <CardDescription>project2.com</CardDescription>
              </div>
              <Button className="ml-auto" size="icon" variant="ghost">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle menu</span>
              </Button>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold">Active Tasks: 15</div>
              <div className="text-sm font-semibold">Your Current Tasks: 5</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <UsersIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">
                    7 Members
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-white dark:bg-gray-800">
            <CardHeader className="flex flex-row items-center gap-4">
              <LayoutPanelLeftIcon className="w-8 h-8 text-red-500 dark:text-red-300" />
              <div className="grid gap-1">
                <CardTitle>Project 3</CardTitle>
                <CardDescription>project3.com</CardDescription>
              </div>
              <Button className="ml-auto" size="icon" variant="ghost">
                <MoreHorizontalIcon className="w-4 h-4" />
                <span className="sr-only">Toggle menu</span>
              </Button>
            </CardHeader>
            <CardContent className="grid gap-2">
              <div className="text-sm font-semibold">Active Tasks: 20</div>
              <div className="text-sm font-semibold">Your Current Tasks: 7</div>
              <div className="flex items-center gap-4 text-sm">
                <div className="flex items-center gap-1">
                  <UsersIcon className="w-4 h-4" />
                  <span className="text-gray-500 dark:text-gray-400">
                    10 Members
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>
          <Button className="bg-white dark:bg-gray-800 w-full h-full flex items-center justify-center text-4xl">
            +
          </Button>
        </div>
      </main>
    </div>
  );
}

//@ts-expect-error
function FrameIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  );
}

//@ts-expect-error

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

//@ts-expect-error

function MoreHorizontalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  );
}

//@ts-expect-error

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  );
}

//@ts-expect-error

function BookOpenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  );
}

//@ts-expect-error

function LayoutPanelLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="18" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
    </svg>
  );
}
