/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Amu9ZRV7sj8
 */
import { SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function TaskTableWithFilters() {
  return (
    <div className="w-full h-full p-4 md:p-6 lg:p-8">
      <div className="grid gap-6 md:gap-8">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold">Task Management</h1>
          <div className="grid grid-cols-3 gap-4">
            <Select defaultValue="all">
              <SelectTrigger className="w-32">Priority</SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="low">Low</SelectItem>
              </SelectContent>
            </Select>
            <Select defaultValue="all">
              <SelectTrigger className="w-32">Project</SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All</SelectItem>
                <SelectItem value="project1">Project 1</SelectItem>
                <SelectItem value="project2">Project 2</SelectItem>
                <SelectItem value="project3">Project 3</SelectItem>
              </SelectContent>
            </Select>
            <Select defaultValue="all">
              <SelectTrigger className="w-32">Stage</SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All</SelectItem>
                <SelectItem value="planning">Planning</SelectItem>
                <SelectItem value="development">Development</SelectItem>
                <SelectItem value="testing">Testing</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="border shadow-sm rounded-lg">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="w-[100px]">Priority</TableHead>
                <TableHead>Project</TableHead>
                <TableHead>Stage</TableHead>
                <TableHead>Deadline</TableHead>
                <TableHead>Description</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow className="bg-red-100">
                <TableCell>High</TableCell>
                <TableCell>Project 1</TableCell>
                <TableCell>Planning</TableCell>
                <TableCell>2024-01-30</TableCell>
                <TableCell>Planning phase for Project 1</TableCell>
              </TableRow>
              <TableRow className="bg-yellow-100">
                <TableCell>Medium</TableCell>
                <TableCell>Project 2</TableCell>
                <TableCell>Development</TableCell>
                <TableCell>2024-02-15</TableCell>
                <TableCell>Development phase for Project 2</TableCell>
              </TableRow>
              <TableRow className="bg-green-100">
                <TableCell>Low</TableCell>
                <TableCell>Project 3</TableCell>
                <TableCell>Testing</TableCell>
                <TableCell>2024-03-01</TableCell>
                <TableCell>Testing phase for Project 3</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}
