/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q1k48fmKxgo
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Slider } from "@/components/ui/slider";
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";

export function TaskFormComponent() {
  return (
    <div className="grid gap-6 w-full max-w-md mx-auto p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
      <h2 className="text-lg font-semibold text-gray-700 dark:text-white">
        Create Task
      </h2>
      <div className="grid gap-2">
        <Label htmlFor="title">Title</Label>
        <Input id="title" placeholder="Enter task title" />
      </div>
      <div className="grid gap-2">
        <Label htmlFor="description">Description</Label>
        <Textarea
          className="min-h-[100px]"
          id="description"
          placeholder="Enter task description"
        />
      </div>
      <div className="grid gap-2">
        <Label htmlFor="progress">Progress</Label>
        <Slider id="progress" max={100} min={0} step={1} />
      </div>
      <div className="grid gap-2">
        <Label>Status</Label>
        <RadioGroup
          className="flex items-center gap-4"
          defaultValue="pending"
          id="status"
        >
          <Label className="flex items-center gap-2" htmlFor="status-pending">
            <RadioGroupItem id="status-pending" value="pending" />
            Pending
          </Label>
          <Label
            className="flex items-center gap-2"
            htmlFor="status-in-progress"
          >
            <RadioGroupItem id="status-in-progress" value="in-progress" />
            In Progress
          </Label>
          <Label className="flex items-center gap-2" htmlFor="status-completed">
            <RadioGroupItem id="status-completed" value="completed" />
            Completed
          </Label>
        </RadioGroup>
      </div>
      <div className="grid gap-2">
        <Label htmlFor="assignee">Assignee</Label>
        <Select>
          <SelectTrigger id="assignee">
            <SelectValue placeholder="Select assignee" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="john">John Doe</SelectItem>
            <SelectItem value="jane">Jane Doe</SelectItem>
            <SelectItem value="mark">Mark Smith</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <Button className="w-full">Save Task</Button>
    </div>
  );
}
