/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YlL52yS5vzs
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function UserCardWithTasks() {
  return (
    <Card className="w-full max-w-md overflow-x-auto">
      <CardHeader className="flex items-center gap-4">
        <Avatar className="h-16 w-16">
          <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
          <AvatarFallback>JP</AvatarFallback>
        </Avatar>
        <div className="space-y-1">
          <h4 className="text-lg font-bold">John Doe</h4>
          <p className="text-sm text-gray-500 dark:text-gray-400">15 Tasks Assigned</p>
        </div>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-2">
        <Badge className="bg-red-200 text-red-700" variant="outline">
          Project Alpha
        </Badge>
        <Badge className="bg-green-200 text-green-700" variant="outline">
          Project Beta
        </Badge>
        <Badge className="bg-blue-200 text-blue-700" variant="outline">
          Project Gamma
        </Badge>
        <Badge className="bg-yellow-200 text-yellow-700" variant="outline">
          Project Delta
        </Badge>
      </CardContent>
      <CardContent className="flex gap-2 overflow-x-auto scroll-snap-x-mandatory">
        <div className="w-1/4 h-24 bg-gray-100 dark:bg-gray-800 p-2 border-t-4 border-red-700 scroll-snap-start">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-yellow-700" />
            <h5 className="text-sm font-bold">Task 1</h5>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400">In Progress</p>
        </div>
        <div className="w-1/4 h-24 bg-gray-100 dark:bg-gray-800 p-2 border-t-4 border-green-700 scroll-snap-start">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-yellow-700" />
            <h5 className="text-sm font-bold">Task 2</h5>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400">In Progress</p>
        </div>
        <div className="w-1/4 h-24 bg-gray-100 dark:bg-gray-800 p-2 border-t-4 border-blue-700 scroll-snap-start">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-yellow-700" />
            <h5 className="text-sm font-bold">Task 3</h5>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400">In Progress</p>
        </div>
        <div className="w-1/4 h-24 bg-gray-100 dark:bg-gray-800 p-2 border-t-4 border-yellow-700 scroll-snap-start">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-yellow-700" />
            <h5 className="text-sm font-bold">Task 4</h5>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400">In Progress</p>
        </div>
        <div className="w-1/4 h-24 bg-gray-100 dark:bg-gray-800 p-2 border-t-4 border-purple-700 scroll-snap-start">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-yellow-700" />
            <h5 className="text-sm font-bold">Task 5</h5>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400">In Progress</p>
        </div>
        <div className="w-1/4 h-24 bg-gray-100 dark:bg-gray-800 p-2 border-t-4 border-pink-700 scroll-snap-start">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-yellow-700" />
            <h5 className="text-sm font-bold">Task 6</h5>
          </div>
          <p className="text-xs text-gray-500 dark:text-gray-400">In Progress</p>
        </div>
      </CardContent>
    </Card>
  )
}
