/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QNm1cdYPkSK
 */
import { Button } from "@/components/ui/button";
import {
  PopoverTrigger,
  PopoverContent,
  Popover,
} from "@/components/ui/popover";
import {
  CommandInput,
  CommandEmpty,
  CommandItem,
  CommandGroup,
  Command,
} from "@/components/ui/command";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";
import { UserIcon, ArrowDownIcon, XIcon } from "lucide-react";
import { TeamDto } from "@/use-cases/team/types";
import { UserDto } from "@/use-cases/user/types";
export function UpdateMembersAndInvite({
  userId,
  team,
  globalUsers,
  teamMembers,
}: {
  userId: string;
  team: TeamDto;
  globalUsers: UserDto[];
  teamMembers: UserDto[];
}) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        {/* <Button
          className="w-[300px] justify-start"
          role="combobox"
          variant="outline"
        > */}
        <div>
          {/* <UserIcon className="mr-2 h-4 w-4 shrink-0 opacity-50" /> */}
          Search members...
        </div>
        {/* </Button> */}
      </PopoverTrigger>
      <PopoverContent className="w-[300px] p-0">
        <Command>
          <CommandInput className="h-9" placeholder="Search members..." />
          <CommandEmpty>No members found.</CommandEmpty>
          <CommandGroup>
            <CommandItem>
              <div className="flex items-center space-x-2">
                <Avatar className="w-4 h-4 border">
                  <AvatarImage alt="@shadcn" src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <span>Jane Doe</span>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size="icon" variant="ghost">
                      {/* <ArrowDownIcon className="w-3 h-3" /> */}
                      Permission
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    <DropdownMenuItem>Admin</DropdownMenuItem>
                    <DropdownMenuItem>Member</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
              <Button className="ml-auto" size="icon" variant="ghost">
                <XIcon className="w-3 h-3" />
                <span className="sr-only">Remove</span>
              </Button>
            </CommandItem>
          </CommandGroup>
        </Command>
      </PopoverContent>
    </Popover>
  );
}
